export const EQUIPOS_API_KEYS = {
  FETCH_EQUIPOS: 'FETCH_EQUIPOS' as const,
  FETCH_EQUIPOS_COUNT: ['FETCH_EQUIPOS', 'COUNT'] as const,
  FETCH_EQUIPO: 'FETCH_EQUIPO' as const,
  FETCH_EQUIPO_DETAIL: ['FETCH_EQUIPO', 'DETAIL'] as const,
};
