import {
  EQUIPOS_API_KEYS,
  EXPENSE_CATEGORIES_API_KEYS,
  USER_API_KEYS,
  STORE_API_KEYS,
  COMBOS_API_KEYS,
  WAREHOUSE_API_KEYS,
} from './index';

export const API_KEYS = {
  ...EQUIPOS_API_KEYS,
  ...USER_API_KEYS,
  ...STORE_API_KEYS,
  ...EXPENSE_CATEGORIES_API_KEYS,
  ...COMBOS_API_KEYS,
  ...WAREHOUSE_API_KEYS,
};
